
 export const settings = {
    headerwithicons: {
      title: 'Custom Header with Icons Title',
      subtitle: 'Custom Header with Icons Subtitle',
      Ftitle: 'Lorem ipsum dolor sit amet,commodo consequat.',
      Ficon: 'bi-balloon',
      Stitle: 'Lorem ipsum dolor sit aaduip ex ea commodo consequat.',
      Sicon: 'bi-balloon',
      Ttitle: 'Lorem ipsum dolor sit amet,commodo consequat.',
      Ticon: 'bi-balloon',
      Ptitle: 'Lorem ipsum dolor sit aaduip ex ea commodo consequat.',
      Picon: 'bi-balloon',
    },
    centeredhero: {
      title: 'Heading Left with Image Title',
      subtitle: 'Heading Left with Image Subtitle',
      imageUrl: 'https://picsum.photos/200/',
    },
    herowithimage: {
      title: 'Heading Right with Image Title',
      subtitle: 'Heading Right with Image Subtitle',
      imageUrl: 'https://picsum.photos/200/',
    },
    verticallycenteredhero: {
      title: 'Centered Hero Title',
      subtitle: 'Centered Hero Subtitle',
      imageUrl: 'https://picsum.photos/400/300',
    },
    columnswithicons: {
      MainTitle: 'Columns with Icons',
      Ftitle: 'Lorem ipsum dolor sit amet,commodo consequat.',
      Fdescription: 'Lorem ipsum dolor sit amet,commodo consequat.',
      Ficon: 'bi bi-0-circle',
      Stitle: 'Lorem ipsum dolor sit aaduip ex ea commodo consequat.',
      Sdescription: 'Lorem ipsum dolor sit aaduip ex ea commodo consequat.',
      Sicon: 'bi bi-0-circle',
      Ttitle: 'Lorem ipstrudx ea commodo consequat.',
      Tdescription: 'Lorem ipstrudx ea commodo consequat.',
      Ticon: 'bi bi-0-circle',
    },
    customcards: {
      MainTitle: 'Columns with Icons',
      Ftitle: 'Lorem ipsum dolor sit amet,commodo consequat.',
      Fimage: 'https://picsum.photos/400/300',
      Stitle: 'Lorem ipsum dolor sit aaduip ex ea commodo consequat.',
      Simage: 'https://picsum.photos/400/300',
      Ttitle: 'Lorem ipstrudx ea commodo consequat.',
      Timage: 'https://picsum.photos/400/300',
    },
    headings: {
      Ftitle: 'Lorem ipsum dolor sit amet,commodo consequat.',
      Fdescription: 'Lorem ipsum dolor sit amet,commodo consequat.',
      Fimage: 'https://picsum.photos/400/300',
      Stitle: 'Lorem ipsum dolor sit aaduip ex ea commodo consequat.',
      Sdescription: 'Lorem ipsum dolor sit aaduip ex ea commodo consequat.',
      Simage: 'https://picsum.photos/400/300',
      Ttitle: 'Lorem ipstrudx ea commodo consequat.',
      Tdescription: 'Lorem ipstrudx ea commodo consequat.',
      Timage: 'https://picsum.photos/400/300',
    },
    headingleftwithimage: {
      title: 'Centered Hero Title',
      subtitle: 'Centered Hero Subtitle',
      imageUrl: 'https://picsum.photos/400/300',
    },
    headingrightwithimage: {
      title: 'Centered Hero Title',
      subtitle: 'Centered Hero Subtitle',
      imageUrl: 'https://picsum.photos/400/300',
    },
    newsletter: {
      titleA: 'Custom dqsdqsdsqNewsletter Title',
      TextB: 'Custom Newsletter Subtitle',
      TextC: 'Custom Newsletter Subtitle',
      Image: 'https://picsum.photos/400/300',
    },
    plateformeabout: {
      title1: 'About Us Title',
      title2: 'About Us Subtitle',
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      imageUrl: 'https://picsum.photos/400/300',
    }
  };