name: Frontend CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Cloner le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Installer les dépendances
        run: npm install

      - name: Builder l'application Angular
        run: npm run build -- --configuration=production

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push image Docker
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-frontend:${{ github.sha }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/mon-frontend:latest \
            --push .

     

